# 1. Usamos la imagen oficial de Node como base
FROM node:lts-alpine

# 2. Actualizamos npm a la última versión global dentro de la imagen
RUN npm install -g npm@latest

# 3. Definimos la carpeta de trabajo por defecto
WORKDIR /usr/src/app
